### PR TITLE
Added EDINA Events

### PR DESCRIPTION
**Pull request by MapNavTom**
Added in the training events EDINA, University of Edinburgh are planning till July.

### CODE REVIEW

**Comment by walkermatt** [comment]
@MapNavTom it looks like the CSV has a few errors, try validating with https://csvlint.io. 

You can validate the file you've committed by entering https://raw.githubusercontent.com/MapNavTom/website/patch-1/_data/osgeouk_training.csv

**Comment by MapNavTom** [comment]
@walkermatt I had some redundant spaces which I have removed.  The validation revealed some other errors that I didn't introduce such as setting the right content type.  Not sure how to fix that sorry!

**Comment by archaeogeek** [comment]
I think there's still a problem with the file, see https://github.com/MapNavTom/website/blob/patch-1/_data/osgeouk_training.csv. This reports a problem with row 11 and an extra comma.

**Comment by archaeogeek** [comment]
Great, thanks

Jo

**Pull request merged**
