### PR TITLE
Update osgeouk_training.csv

### PR DESCRIPTION
**Pull request by ghost**
2018 Courses added from thinkwhere

### CODE REVIEW

**Comment by archaeogeek** [comment]
There's still a problem in this csv- see https://github.com/willadam/website/blob/patch-2/_data/osgeouk_training.csv. Looks like a stray comma or similar.

**Comment by walkermatt** [comment]
Hi @willadam, can you try running through https://csvlint.io/.

**Comment by ghost** [comment]
Hi, just wondering if everything is ok with the updated file and if I need to do anything more to get it to be published?

Thanks.

**Comment by walkermatt** [comment]
All merged :+1:

**Comment by ghost** [comment]
Great thanks!

**Pull request merged**
