### PR TITLE
change of Simoes presenting team

### PR DESCRIPTION
**Pull request by ajgwords**

### CODE REVIEW

**Comment by archaeogeek** [comment]
Can we check spelling- I'm guessing this should be Joanna Simones?

**Comment by antonys** [comment]
Simoes is correct I think https://thegeomob.com/podcast/episode-4

**Comment by tomchadwin** [comment]
It's Joana Simoes.
________________________________

**Comment by archaeogeek** [comment]
Who knew? It's probably not JJoana with two J's though :-)

**Comment by stevenfeldman** [comment]
Its Joana Simoes
______
Steven

Unusual maps in strange places -  mappery.org <http://mappery.org/>

Subscribe to my weekly “Maps in the Wild <http://eepurl.com/dKStT-/>” newsletter

**Pull request closed without merging**
