### PR TITLE
Update osgeouk_training.csv

### PR DESCRIPTION
**Pull request by crowtherd**
David Crowther has added Cadlines training courses

### CODE REVIEW

**Comment by crowtherd** [comment]
please can you check the new Cadline training courses and then merge with live, many thanks David Crowther

**Comment by archaeogeek** [comment]
Hi David, Thanks for this- take a look at https://github.com/crowtherd/website/blob/patch-2/_data/osgeouk_training.csv though, you have a formatting issue to correct. Happy to merge as soon as the file is valid.

**Comment by walkermatt** [comment]
@crowtherd see: https://csvlint.io/validation/5a061a922da2ec0004000037

**Comment by crowtherd** [comment]
Thanks Jo, I will amend and re submit the dates on Friday.

Thanks again
Best regards David.C

**Comment by crowtherd** [comment]
Hi Jo,.
I used your link and edited the online file, and committed the changes. I didn't know whether to choose update current branch or create a new pull request. So I chose the first option, Hopefully you can see my recommended changes?
thanks in advancebest regardsDavid.C

David Crowther Mobile: 07813 832552 

    On Thursday, 9 November 2017, 17:54, Jo Cook <notifications@github.com> wrote:
 

 Hi David, Thanks for this- take a look at https://github.com/crowtherd/website/blob/patch-2/_data/osgeouk_training.csv though, you have a formatting issue to correct. Happy to merge as soon as the file is valid.—

**Comment by archaeogeek** [comment]
Hi David,

Unfortunately there have been changes since you pulled the file, so there are now conflicts! The easiest approach will be to close this pull request, and for you to create a new one and add your changes again. Sorry about that!

Jo

**Comment by crowtherd** [comment]
Thanks for getting back to me Jo. I will try again, and hope we are 3rd time lucky. 
Best regards
David.C

**Comment by crowtherd** [comment]
Hi Jo, I have resubmitted a Pull request to add our 9 courses to the training calendar. Hopefully I have edited against the latest and live list so it should simply be a case of inserting these 9 new items.
thanks in advancebest regardsDavid.C
 David Crowther Mobile: 07813 832552 

    On Wednesday, 22 November 2017, 17:36, David Crowther <crowtherd@ymail.com> wrote:
 

 Thanks for getting back to me Jo. I will try again, and hope we are 3rd time lucky. Best regardsDavid.C

Sent from David's iPhone
On 22 Nov 2017, at 16:11, Jo Cook <notifications@github.com> wrote:


Hi David,Unfortunately there have been changes since you pulled the file, so there are now conflicts! The easiest approach will be to close this pull request, and for you to create a new one and add your changes again. Sorry about that!Jo—

**Pull request closed without merging**
